graphite:
  api-base-url: ${GRAPHITE_API_BASE_URL:https://poc.projectgraphite.com/api/public/api/v1}
  auth-url: ${GRAPHITE_AUTH_URL:https://poc.projectgraphite.com/api/oauth/token}
  client-id: ${GRAPHITE_CLIENT_ID}
  client-secret: ${GRAPHITE_CLIENT_SECRET}
  interface-name: ${GRAPHITE_INTERFACE_NAME:QAD}
  limit: ${GRAPHITE_LIMIT:100}
  sync:
    cron: ${GRAPHITE_SYNC_CRON:0 */2 * * * *}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /graphite-client

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    root: INFO
    java.com.rassini.graphite_client.service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
