graphite:
  api-base-url: ${GRAPHITE_API_BASE_URL:https://poc.projectgraphite.com/api/public/api/v1}
  auth-url: ${GRAPHITE_AUTH_URL:https://poc.projectgraphite.com/api/oauth/token}
  client-id: ${GRAPHITE_CLIENT_ID}
  client-secret: ${GRAPHITE_CLIENT_SECRET}
  interface-name: ${GRAPHITE_INTERFACE_NAME:QAD}
  limit: ${GRAPHITE_LIMIT:100}
  sync:
    cron: ${GRAPHITE_SYNC_CRON:0 */15 * * * *}


app:
  xml:
    output-path: ${XML_OUTPUT_PATH:C:/temp}

server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /graphite-client

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  file:
    name: logs/graphite-client.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/archive/graphite-client.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 20MB
      max-history: 5
      total-size-cap: 500MB
      clean-history-on-start: true
  level:
    root: INFO
    com.rassini.graphite_client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: graphite-client
    export:
      prometheus:
        enabled: true
