package com.rassini.graphite_client.service.validation.model;

public enum IssueType {
    REQUIRED_FIELD_MISSING,
    REQUIRED_FIELD_BLANK,
    CATALOG_EQUIVALENCE_MISSING,
    UNSUPPORTED_BUSINESS_UNIT,
    BANK_ACCOUNT_MISSING,
    BANK_INFO_INCOMPLETE,
    AMBIGUOUS_NODE,
    TRANSFORMATION_ERROR,
    GENERATION_EXCEPTION
}
