package com.rassini.graphite_client.entity;

public enum ProviderState {
    DESCARGA,
    PROCESSINGJPA,
    PROCESSINGXMLOC,
    PROCESSINGXMLPN,
    PROCESSINGXMLFRN,
    PROCESSINGXMLBRK,
    PROCESSINGXMLCOMPLETE,
    CONFIRMADOACK,
    ERRORMAPPING,
    ERRORMAPOC,
    ERRORMAPFRENOS,
    ERRORMAPBREAKES,
    ERRORMAPBYPASA,
    ERRORMAPPN,


}
